#!/usr/bin/bash

if [ $# -eq 0 ]
then
  echo "Usage: ./BUILD /prefix/path"
  exit 1
fi

mkdir build64
cd build64
../configure --target riscv64-unknown-elf --prefix "$1" CXXFLAGS='-g3' CFLAGS='-g3'
make -j$nproc
make install
cd -


